language: node_js
node_js:
  - "node"

stages:
  - name: deploy
    if: branch = feature/enable-travis-ci

jobs:
  include:
    - stage: deploy
      name: 'Deploy to master (GH pages)'
      install: npm ci
      if: branch = feature/enable-travis-ci
      script: bash .scripts/deploy.sh
