language: node_js
node_js:
  - "node"

jobs:
  include:
    - stage: deploy
      name: 'Deploy to master (GH pages)'
      install: npm ci
      if: branch = develop AND type != pull_request
      script: bash .scripts/deploy.sh
